using System.Collections;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Runtime.InteropServices.WindowsRuntime;
using System.Runtime.Serialization;
using System.Text.RegularExpressions;
using NUnit.Framework;
using UnityEditor;
using UnityEngine;
using UnityEngine.TestTools;
using WitchOS;

namespace Tests
{
    public class SetCommandTests
    {
        public class TerminalStub : ITerminal
        {
            public bool CurrentlyEvaluating => true;
            public bool WasInterrupted => false;

            public IList<string> InputHistory
            {
                get => new List<string>();
                set { }
            }

            public IList<string> OutputHistory
            {
                get => new List<string>();
                set { }
            }

            public string LastOutputLine
            {
                get => "";
                set { }
            }

            public void Print (string output) { }

            public void PrintEmptyLine () { }

            public void PrintLine (string line) { }
        }

        SetCommand setCommand;
        EnvironmentVariableState environmentVariableState;

        [SetUp]
        public void GrabAssets ()
        {
            setCommand = AssetDatabase.LoadAssetAtPath<SetCommand>("Assets/ScriptableObjects/AutoGenerated/TerminalCommands/SetCommand.asset");
            environmentVariableState = AssetDatabase.LoadAssetAtPath<EnvironmentVariableState>("Assets/ScriptableObjects/Systems/Environment Variable State System.asset");
        }

        [Test]
        public void EnvironmentIsEmptyWhenNothingIsSet ()
        {
            Assert.IsEmpty(environmentVariableState.GetEnvironmentVariable("key"));
            Assert.IsEmpty(environmentVariableState.GetEnvironmentVariable("test"));
            Assert.IsEmpty(environmentVariableState.GetEnvironmentVariable("aura"));
            Assert.IsEmpty(environmentVariableState.GetEnvironmentVariable("target"));
        }

        [UnityTest]
        public IEnumerator SimpleArgumentListIsSet ()
        {
            string key = "key";
            string value = "value";

            yield return setCommand.Evaluate(new TerminalStub(), new string[] { "set", key, value });

            Assert.AreEqual(value, environmentVariableState.GetEnvironmentVariable(key));
        }

        [UnityTest]
        public IEnumerator ComplexArgumentListIsSet ()
        {
            string[] args = new string[] { "set", "key", "to", "complex", "value", "list" };

            yield return setCommand.Evaluate(new TerminalStub(), args);

            Assert.AreEqual(string.Join(" ", args.Skip(2)), environmentVariableState.GetEnvironmentVariable("key"));
        }
    }
}
