name: Test, Build and Release

on:
  push:
    branches:
      - master
      - bug/**
      - feature/ci-cd # TODO: replace with **

env:
  UNITY_VERSION: 2019.4.12f1
  UNITY_LICENSE: ${{ secrets.UNITY_LICENSE }}
  ITCH_GAME: witchos-secret-version
  ITCH_USER: crass_sandwich
  BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
  SUPPORTED_PLATFORMS:
  # builder-name: name used for unity-builder action
  # itch-name: name used for butler-publish-itchio-action
    - builder-name: WebGL
      itch-name: webgl
    - builder-name: StandaloneWindows
      itch-name: win
    - builder-name: StandaloneOSX
      itch-name: osx

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        testMode:
          - playmode
          - editmode
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-test
          restore-keys: Library-
      - uses: webbertakken/unity-test-runner@v1.4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          testMode: ${{ matrix.testMode }}
      - uses: actions/upload-artifact@v2
        with:
          name: test-report
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
      # filter syntax (*.) gets you just an array of the builder-name values
        targetPlatform: ${{ env.SUPPORTED_PLATFORMS.*.builder-name }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/cache@v1.1.0
        with:
          path: Library
          key: Library-${{ matrix.targetPlatform }}
          restore-keys: Library-
      - uses: webbertakken/unity-builder@v1.4
        with:
          unityVersion: ${{ env.UNITY_VERSION }}
          targetPlatform: ${{ matrix.targetPlatform }}
      - uses: actions/upload-artifact@v2
        with:
          name: build-${{ matrix.targetPlatform }}
          path: builds
  release:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        targetPlatform: ${{ env.SUPPORTED_PLATFORMS }}
    steps:
      - uses: actions/checkout@v2
        with:
          lfs: true
      - uses: actions/download-artifact@v2
        with:
          path: builds
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          PACKAGE: builds/build-${{ matrix.targetPlatform.builder-name }}
          CHANNEL: ${{ matrix.targetPlatform.itch-name }}
