name: 'UCB: Create Build Target'


on:
  workflow_dispatch: ~
  create:
    branches: [ feature/** ]


env:
  REQUEST_BODY_CONTENT_DIRECTORY: './workflows/create_build_target_request_bodies/'
  REQUEST_URL: 'https://build-api.cloud.unity3d.com/api/v1/orgs/1366086/projects/b19fc897-adf6-4d9b-bef5-3bb4daf59bbc/buildtargets'


jobs:
  create-target:
    runs-on: ubuntu-latest

    strategy:
      fail-fast: false
      matrix:
        platform:
          - webgl
          - standaloneosxuniversal
          - standalonewindows64

    steps:
      - name: 'Grab branch name'
        uses: nelonoel/branch-name@v1

      - name: 'Read config file and replace placeholders'
        id: get-config
        uses: bluwy/substitute-string-action@v1
        with:
          _input_file: ./.github/workflows/create-build-target-request-body.json
          NAME_PLACEHOLDER: ${{ BRANCH_NAME }} - ${{ matrix.platform }}
          PLATFORM_PLACEHOLDER: ${{ matrix.platform }}
          BRANCH_PLACEHOLDER: ${{ BRANCH_NAME }}

      - name: 'Send create-target request'
        uses: fjogeleit/http-request-action@v1.5.0
        with:
          url: ${{ REQUEST_URL }}
          method: POST
          customHeaders: '{"Authorization": "Basic ${{ secrets.UNITY_CLOUD_BUILD_API_KEY }}"}'
          data: ${{ steps.get-config.outputs.result }}
