name: 'UCB: Create Build Target'


on:
  create:
    branches: [ feature/** ]


env:
  AUTHORIZATION_HEADER: '{"Authorization": "Basic ${{ secrets.UNITY_CLOUD_BUILD_API_KEY }}"}'
  REQUEST_TIMEOUT: 30000


jobs:
  create-target:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        platform:
          - webgl
          - standaloneosxuniversal
          - standalonewindows64

    steps:
      - uses: actions/checkout@v2

      - name: 'Grab branch name'
        uses: nelonoel/branch-name@v1

      - name: 'Read config file and replace placeholders'
        id: get-config
        uses: bluwy/substitute-string-action@v1
        with:
          _input-file: ./.github/workflows/create-build-target-request-body.json
          NAME_PLACEHOLDER: feature - ${{ env.BRANCH_NAME }} - ${{ matrix.platform }}
          PLATFORM_PLACEHOLDER: ${{ matrix.platform }}
          BRANCH_PLACEHOLDER: feature/${{ env.BRANCH_NAME }}

      - name: 'Send create-target request'
        id: create-target-request
        uses: fjogeleit/http-request-action@v1.5.0
        with:
          url: https://build-api.cloud.unity3d.com/api/v1/orgs/1366086/projects/b19fc897-adf6-4d9b-bef5-3bb4daf59bbc/buildtargets
          method: POST
          customHeaders: ${{ env.AUTHORIZATION_HEADER }}
          timeout: ${{ env.REQUEST_TIMEOUT }}
          data: ${{ steps.get-config.outputs.result }}
      
      - name: 'Trigger first build'
        uses: fjogeleit/http-request-action@v1.5.0
        with:
          url: https://build-api.cloud.unity3d.com/api/v1/orgs/1366086/projects/b19fc897-adf6-4d9b-bef5-3bb4daf59bbc/buildtargets/${{ fromJSON(steps.create-target-request.outputs.response).buildtargetid }}/builds
          method: POST
          customHeaders: ${{ env.AUTHORIZATION_HEADER }}
          timeout: ${{ env.REQUEST_TIMEOUT }}
